//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "characters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uid: String,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub creator_uid: String,
    pub avatar_uid: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::chat_characters::Entity")]
    ChatCharacters,
    #[sea_orm(
        belongs_to = "super::files::Entity",
        from = "Column::AvatarUid",
        to = "super::files::Column::Uid",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Files,
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::CreatorUid",
        to = "super::users::Column::Uid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::chat_characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatCharacters.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Files.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        super::chat_characters::Relation::Chats.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::chat_characters::Relation::Characters.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
