//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "chat_characters")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chat_uid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub character_uid: String,
    pub connected_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::characters::Entity",
        from = "Column::CharacterUid",
        to = "super::characters::Column::Uid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Characters,
    #[sea_orm(
        belongs_to = "super::chats::Entity",
        from = "Column::ChatUid",
        to = "super::chats::Column::Uid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chats,
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Characters.def()
    }
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
