//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uid: String,
    #[sea_orm(unique)]
    pub filename: String,
    pub uploaded_by: String,
    pub scope_kind: String,
    pub scope_owner_id: String,
    pub scope_entity_id: Option<String>,
    pub uploaded_at: DateTime,
    pub status: String,
    pub original_name: String,
    pub content_type: String,
    pub size: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::characters::Entity")]
    Characters,
    #[sea_orm(has_many = "super::personas::Entity")]
    Personas,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::ScopeOwnerId",
        to = "super::users::Column::Uid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UploadedBy",
        to = "super::users::Column::Uid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users1,
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Characters.def()
    }
}

impl Related<super::personas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Personas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
