//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uid: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub author_persona_uid: String,
    pub author_character_uid: String,
    pub chat_uid: String,
    pub reply_to_message_uid: String,
    pub is_removed: bool,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::characters::Entity",
        from = "Column::AuthorCharacterUid",
        to = "super::characters::Column::Uid",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Characters,
    #[sea_orm(
        belongs_to = "super::chats::Entity",
        from = "Column::ChatUid",
        to = "super::chats::Column::Uid",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chats,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ReplyToMessageUid",
        to = "Column::Uid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(
        belongs_to = "super::personas::Entity",
        from = "Column::AuthorPersonaUid",
        to = "super::personas::Column::Uid",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Personas,
}

impl Related<super::characters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Characters.def()
    }
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl Related<super::personas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Personas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
