/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainLayoutRouteImport } from './routes/_main-layout'
import { Route as MainLayoutHomeRouteImport } from './routes/_main-layout/home'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutRoute = MainLayoutRouteImport.update({
  id: '/_main-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const MainLayoutHomeRoute = MainLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/home': typeof MainLayoutHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof MainLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/home': typeof MainLayoutHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main-layout': typeof MainLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_main-layout/home': typeof MainLayoutHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/home'
  id: '__root__' | '/_main-layout' | '/login' | '/_main-layout/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainLayoutRoute: typeof MainLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout': {
      id: '/_main-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main-layout/home': {
      id: '/_main-layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainLayoutHomeRouteImport
      parentRoute: typeof MainLayoutRoute
    }
  }
}

interface MainLayoutRouteChildren {
  MainLayoutHomeRoute: typeof MainLayoutHomeRoute
}

const MainLayoutRouteChildren: MainLayoutRouteChildren = {
  MainLayoutHomeRoute: MainLayoutHomeRoute,
}

const MainLayoutRouteWithChildren = MainLayoutRoute._addFileChildren(
  MainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainLayoutRoute: MainLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
